DownloadsPath: /Users/mitisdre/Downloads
FileTypes:
  Images: [".jpg", ".jpeg", ".png", ".gif", ".bmp", ".tiff", ".svg"]
  Documents: [".pdf", ".doc", ".docx", ".txt", ".xls", ".xlsx", ".ppt", ".pptx"]
  Videos: [".mp4", ".avi", ".mov", ".mkv", ".wmv"]
  Audio: [".mp3", ".wav", ".flac", ".aac", ".ogg"]
  Archives: [".zip", ".tar", ".gz", ".rar", ".7z"]
  Code: [".py", ".js", ".html", ".css", ".java", ".c", ".cpp", ".json", ".xml", ".yml", ".yaml"]
  Others: []